//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinical_Trial_with_Audit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Audit_user_Registration
    {
        public int Audit_No { get; set; }
        public int Reg_No { get; set; }
        public int Trial_No { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> Registration_date { get; set; }
        public string Approve_Status { get; set; }
        public string operation { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> audit_date { get; set; }
    }
}
