//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinical_Trial_with_Audit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Clinical_Trials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Clinical_Trials()
        {
            this.Tbl_Register_user = new HashSet<Tbl_Register_user>();
            this.Tbl_User_Registration = new HashSet<Tbl_User_Registration>();
        }
    
        public int Trial_No { get; set; }
        public string Project_Name { get; set; }
        public string Project_Code { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<int> Trial_Type_No { get; set; }
        public string Owned_by { get; set; }
    
        public virtual Tbl_Trial_Type Tbl_Trial_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Register_user> Tbl_Register_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_User_Registration> Tbl_User_Registration { get; set; }
    }
}
