//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinical_Trial_with_Audit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_User_Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_User_Registration()
        {
            this.AuditLogs = new HashSet<AuditLog>();
        }

        [Key]
        [Display(Name = "Register Number")]
        public int Reg_No { get; set; }

        [Display(Name = "Trial Number")]
        [Required(ErrorMessage = "Trial Number is Required")]
        public int Trial_No { get; set; }


        [Display(Name = "Full Name")]
        [Required(ErrorMessage = "Full Name is Required")]
        public string FullName { get; set; }

        [Display(Name = "Date of Birth")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Dob is Required")]
        public Nullable<System.DateTime> Dob { get; set; }

        [Display(Name = "Mobile Number")]

        [Required(ErrorMessage = "Mob is Required")]
        public string Mob { get; set; }

        [Display(Name = "Address")]

        [Required(ErrorMessage = "Address is Required")]
        public string Address1 { get; set; }

        [Display(Name = "Existing Condition")]

        [Required(ErrorMessage = "Existing Condition is Required")]
        public string Existing_Condition { get; set; }

        [Display(Name = "Registration date")]
        [DataType(DataType.DateTime)]
        // [RegularExpression(@"(((0|1)[0-9]|2[0-9]|3[0-1])\/(0[1-9]|1[0-2])\/((19|20)\d\d))$", ErrorMessage = "Invalid date format.")]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}", ApplyFormatInEditMode = false)]
        [Required(ErrorMessage = "Registration date is Required")]
        public Nullable<System.DateTime> Registration_date { get; set; }

        public string Approve_Status { get; set; }

        public Nullable<int> Is_Active { get; set; }

        public virtual Tbl_Clinical_Trials Tbl_Clinical_Trials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditLog> AuditLogs { get; set; }
    }
}
