//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinical_Trial_with_Audit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        public int Userid { get; set; }
        public string Username { get; set; }
        public string password { get; set; }
        public string role { get; set; }
    }
}
