//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinical_Trial_with_Audit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VM_New_Audit
    {
        public System.Guid Id { get; set; }
        public string AuditType { get; set; }
        public string TableName { get; set; }
        public int Reg_No { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public System.DateTime Date { get; set; }
        public string UserName { get; set; }
        public string column_name { get; set; }
    }
}
