//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinical_Trial_with_Audit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Trial
    {
        public int Trial_No { get; set; }
        public string Project_Name { get; set; }
        public string Project_Code { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Owned_by { get; set; }
        public int Trial_Type_No { get; set; }
        public string description { get; set; }
        public string Trial_Type { get; set; }
    }
}
